# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  
 config.vm.box = "ubuntu/trusty64"

 config.vm.network "public_network", ip: "192.168.1.100", "forwarded_port", guest: 80, host: 8080

  # config.vm.synced_folder "../data", "/vagrant_data"
  # Provider-specific configuration so you can fine-tune various
  
 config.vm.provider "virtualbox" do |vb|

  vb.name = "Webserver-VM-M300-LB02-Muharemi"
  vb.gui = true
  vb.memory = "1024"

end


  config.vm.provision "shell", inline: <<-SHELL
  apt-get update
  apt-get install -y apache2

  SHELL

end
